# Generated by Django 6.0.3 on 2026-03-28 14:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the vocabulary. Must be unique.",
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier. Auto-generated from name if left blank (ICV_TAXONOMY_AUTO_SLUG=True).",
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the vocabulary's purpose.",
                        verbose_name="description",
                    ),
                ),
                (
                    "vocabulary_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("hierarchical", "Hierarchical"),
                            ("faceted", "Faceted"),
                        ],
                        default="flat",
                        help_text="Structural type of this vocabulary. Cannot be changed once terms exist (BR-TAX-002).",
                        max_length=20,
                        verbose_name="vocabulary type",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True,
                        help_text="If True, new terms may be added freely. If False, the vocabulary is closed to new terms (BR-TAX-003).",
                        verbose_name="is open",
                    ),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=True,
                        help_text="If True, objects may be tagged with multiple terms from this vocabulary.",
                        verbose_name="allow multiple",
                    ),
                ),
                (
                    "max_depth",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum allowed term depth (zero-based). Null means unlimited. Only meaningful for hierarchical vocabularies.",
                        null=True,
                        verbose_name="max depth",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary key/value metadata. Must be a JSON object.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive vocabularies are hidden from default querysets.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "vocabulary",
                "verbose_name_plural": "vocabularies",
                "db_table": "icv_taxonomy_vocabulary",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "ICV_TAXONOMY_VOCABULARY_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Materialised path string (e.g. '0001/0002/0003'). Managed by icv-tree — do not edit directly.",
                        max_length=255,
                        unique=True,
                        verbose_name="path",
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        editable=False,
                        help_text="Zero-based depth in the tree. Root nodes have depth=0.",
                        verbose_name="depth",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        editable=False,
                        help_text="Zero-based sibling ordering index within the parent. Used to compute path step values.",
                        verbose_name="order",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable term label.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier, unique within its vocabulary. Auto-generated from name if left blank (BR-TAX-007).",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of this term.",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive terms are hidden from default querysets.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary key/value metadata. Must be a JSON object.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent node. Null for root nodes.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="icv_taxonomy.term",
                        verbose_name="parent",
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        help_text="The vocabulary this term belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="icv_taxonomy.vocabulary",
                        verbose_name="vocabulary",
                    ),
                ),
            ],
            options={
                "verbose_name": "term",
                "verbose_name_plural": "terms",
                "db_table": "icv_taxonomy_term",
                "ordering": ["path"],
                "abstract": False,
                "unique_together": {("vocabulary", "slug")},
                "swappable": "ICV_TAXONOMY_TERM_MODEL",
            },
        ),
        migrations.CreateModel(
            name="TermAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="Primary key of the associated object, stored as a string to support integer, UUID, and other PK types.",
                        max_length=255,
                        verbose_name="object ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of this term association within the object.",
                        verbose_name="order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this association was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Content type of the associated object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="The taxonomy term applied to the object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="icv_taxonomy.term",
                        verbose_name="term",
                    ),
                ),
            ],
            options={
                "verbose_name": "term association",
                "verbose_name_plural": "term associations",
                "db_table": "icv_taxonomy_termassociation",
                "ordering": ["order", "created_at"],
                "abstract": False,
                "unique_together": {("term", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="TermRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("synonym", "Synonym"),
                            ("related", "Related"),
                            ("see_also", "See also"),
                            ("broader", "Broader"),
                            ("narrower", "Narrower"),
                        ],
                        help_text="Semantic type of the relationship between the two terms.",
                        max_length=20,
                        verbose_name="relationship type",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary key/value metadata. Must be a JSON object.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "term_from",
                    models.ForeignKey(
                        help_text="Origin term of the relationship.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="icv_taxonomy.term",
                        verbose_name="term from",
                    ),
                ),
                (
                    "term_to",
                    models.ForeignKey(
                        help_text="Target term of the relationship.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="icv_taxonomy.term",
                        verbose_name="term to",
                    ),
                ),
            ],
            options={
                "verbose_name": "term relationship",
                "verbose_name_plural": "term relationships",
                "db_table": "icv_taxonomy_termrelationship",
                "abstract": False,
                "unique_together": {("term_from", "term_to", "relationship_type")},
            },
        ),
    ]
