# Generated by Django 6.0.3 on 2026-03-31 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_taxonomy", "0002_term_scoped_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="vocabulary",
            field=models.ForeignKey(
                help_text="The vocabulary this term belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to=settings.ICV_TAXONOMY_VOCABULARY_MODEL,
                verbose_name="vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="termassociation",
            name="term",
            field=models.ForeignKey(
                help_text="The taxonomy term applied to the object.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to=settings.ICV_TAXONOMY_TERM_MODEL,
                verbose_name="term",
            ),
        ),
        migrations.AlterField(
            model_name="termrelationship",
            name="term_from",
            field=models.ForeignKey(
                help_text="Origin term of the relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_from_set",
                to=settings.ICV_TAXONOMY_TERM_MODEL,
                verbose_name="term from",
            ),
        ),
        migrations.AlterField(
            model_name="termrelationship",
            name="term_to",
            field=models.ForeignKey(
                help_text="Target term of the relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_to_set",
                to=settings.ICV_TAXONOMY_TERM_MODEL,
                verbose_name="term to",
            ),
        ),
    ]
