# Generated by Django 6.0.3 on 2026-03-22 19:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text='Advertising system domain, e.g. "google.com".',
                        max_length=200,
                    ),
                ),
                (
                    "publisher_id",
                    models.CharField(
                        help_text="Publisher account ID assigned by the advertising system.",
                        max_length=200,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[("DIRECT", "Direct"), ("RESELLER", "Reseller")],
                        help_text="Whether the seller is a direct publisher or a reseller.",
                        max_length=10,
                    ),
                ),
                (
                    "certification_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional TAG-ID certification authority ID.",
                        max_length=200,
                    ),
                ),
                (
                    "is_app_ads",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this entry belongs to app-ads.txt; otherwise ads.txt.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this entry is included when rendering the ads file.",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Optional comment for internal reference.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "ads.txt entry",
                "verbose_name_plural": "ads.txt entries",
                "db_table": "icv_sitemaps_ads_entry",
                "ordering": ["domain", "publisher_id"],
            },
        ),
        migrations.CreateModel(
            name="RobotsRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        default="*",
                        help_text='User agent string, e.g. "*", "Googlebot", or "GPTBot".',
                        max_length=200,
                    ),
                ),
                (
                    "directive",
                    models.CharField(
                        choices=[("allow", "Allow"), ("disallow", "Disallow")],
                        help_text="Whether to allow or disallow the specified path.",
                        max_length=10,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        default="/",
                        help_text='URL path pattern, e.g. "/admin/", "/api/", or "/*.pdf$".',
                        max_length=500,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sort order within the user agent group (lower = first).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rule is included when rendering robots.txt.",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Optional comment explaining the purpose of this rule.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "robots.txt rule",
                "verbose_name_plural": "robots.txt rules",
                "db_table": "icv_sitemaps_robots_rule",
                "ordering": ["user_agent", "order"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "user_agent", "order"],
                        name="icv_sm_robots_tnt_ua_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SitemapSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Logical section name, e.g. "products" or "articles".',
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier for multi-tenant setups. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "model_path",
                    models.CharField(
                        help_text='Dotted path to the Django model class, e.g. "myapp.models.Product".',
                        max_length=500,
                    ),
                ),
                (
                    "sitemap_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("news", "News"),
                        ],
                        default="standard",
                        help_text="Type of sitemap to generate for this section.",
                        max_length=20,
                    ),
                ),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        default="daily",
                        help_text="Default change frequency for URLs in this section.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default="0.5",
                        help_text="Default URL priority for this section (0.0-1.0).",
                        max_digits=2,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this section is included in sitemap generation.",
                    ),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this section needs regeneration.",
                    ),
                ),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful generation run.",
                        null=True,
                    ),
                ),
                (
                    "url_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total URLs across all files for this section.",
                    ),
                ),
                (
                    "file_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of XML files generated for this section.",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Section-specific configuration overrides (JSON).",
                    ),
                ),
            ],
            options={
                "verbose_name": "sitemap section",
                "verbose_name_plural": "sitemap sections",
                "db_table": "icv_sitemaps_section",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_stale"],
                        name="icv_sm_sect_actv_stl_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("name", "tenant_id"), name="icv_sm_sect_name_tnt_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="SitemapGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generate_section", "Generate section"),
                            ("generate_all", "Generate all"),
                            ("generate_index", "Generate index"),
                            ("ping", "Ping search engines"),
                        ],
                        help_text="Action type for this generation run.",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        help_text="Current status of this generation run.",
                        max_length=20,
                    ),
                ),
                (
                    "url_count",
                    models.PositiveIntegerField(default=0, help_text="Total URLs generated in this run."),
                ),
                (
                    "file_count",
                    models.PositiveIntegerField(default=0, help_text="Number of files written in this run."),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, help_text="Generation time in milliseconds."),
                ),
                (
                    "detail",
                    models.TextField(blank=True, help_text="Error message or summary for this run."),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Section that was generated. Null for a full-site regeneration run.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_logs",
                        to="icv_sitemaps.sitemapsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "sitemap generation log",
                "verbose_name_plural": "sitemap generation logs",
                "db_table": "icv_sitemaps_generation_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryFileConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("llms_txt", "llms.txt"),
                            ("security_txt", "security.txt"),
                            ("humans_txt", "humans.txt"),
                        ],
                        help_text="The discovery file this record configures.",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Raw file content to serve at the file's canonical URL."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this file is served when requested.",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last edited this configuration.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "discovery file configuration",
                "verbose_name_plural": "discovery file configurations",
                "db_table": "icv_sitemaps_discovery_config",
                "ordering": ["file_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file_type", "tenant_id"),
                        name="icv_sm_disc_type_tnt_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SitemapFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="File sequence number within the section (0-based).",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        help_text='Path to the XML file in storage, e.g. "sitemaps/products-0.xml".',
                        max_length=500,
                    ),
                ),
                (
                    "url_count",
                    models.PositiveIntegerField(default=0, help_text="Number of URLs in this file."),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(default=0, help_text="Size of the generated XML file in bytes."),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the file contents for change detection.",
                        max_length=64,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this file was generated."),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The parent sitemap section that produced this file.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="icv_sitemaps.sitemapsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "sitemap file",
                "verbose_name_plural": "sitemap files",
                "db_table": "icv_sitemaps_file",
                "ordering": ["section", "sequence"],
                "constraints": [
                    models.UniqueConstraint(fields=("section", "sequence"), name="icv_sm_file_sect_seq_uniq")
                ],
            },
        ),
    ]
