# Generated by Django 6.0.3 on 2026-03-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_sitemaps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemapsection",
            name="model_path",
            field=models.CharField(
                help_text='Django model in "app_label.ModelName" format, e.g. "catalog.Product".',
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="sitemapsection",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Section-specific configuration overrides (JSON).",
            ),
        ),
    ]
