# Generated by Django 5.2.13 on 2026-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icv_sitemaps", "0002_alter_sitemapsection_model_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robotsrule",
            name="directive",
            field=models.CharField(
                choices=[
                    ("allow", "Allow"),
                    ("disallow", "Disallow"),
                    ("crawl-delay", "Crawl-delay"),
                    ("sitemap", "Sitemap"),
                    ("host", "Host"),
                ],
                help_text="Robots.txt directive, e.g. Allow, Disallow, or Crawl-delay.",
                max_length=20,
            ),
        ),
    ]
