# Generated by Django 5.2.13 on 2026-04-14 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icv_sitemaps", "0003_alter_robotsrule_directive"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        help_text="Request path that returned 404.",
                        max_length=2000,
                        verbose_name="path",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of times this path returned 404.",
                        verbose_name="hit count",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this 404 was first recorded.",
                        verbose_name="first seen at",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this 404 was most recently recorded.",
                        verbose_name="last seen at",
                    ),
                ),
                (
                    "referrers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Top referrers for this 404, as {url: count} pairs.",
                        verbose_name="referrers",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether a redirect rule has been created for this path.",
                        verbose_name="resolved",
                    ),
                ),
            ],
            options={
                "verbose_name": "404 log entry",
                "verbose_name_plural": "404 log entries",
                "db_table": "icv_sitemaps_redirect_log",
                "ordering": ["-hit_count"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("path", "tenant_id"), name="icv_sm_rdlog_path_tnt_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RedirectRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for this redirect rule.",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("prefix", "Prefix"),
                            ("regex", "Regex"),
                        ],
                        default="exact",
                        help_text="How to match the source pattern against the request path.",
                        max_length=10,
                        verbose_name="match type",
                    ),
                ),
                (
                    "source_pattern",
                    models.CharField(
                        db_index=True,
                        help_text="URL path to match (exact path, prefix, or regex).",
                        max_length=2000,
                        verbose_name="source pattern",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Target URL. Leave blank for 410 Gone responses.",
                        max_length=2000,
                        verbose_name="destination",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (301, "301 Moved Permanently"),
                            (302, "302 Found"),
                            (307, "307 Temporary Redirect"),
                            (308, "308 Permanent Redirect"),
                            (410, "410 Gone"),
                        ],
                        default=301,
                        help_text="HTTP status code for the redirect response.",
                        verbose_name="status code",
                    ),
                ),
                (
                    "preserve_query_string",
                    models.BooleanField(
                        default=True,
                        help_text="Carry the original query string to the destination URL.",
                        verbose_name="preserve query string",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are not evaluated.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers are evaluated first.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is automatically skipped after this time. Null means never expires.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been matched.",
                        verbose_name="hit count",
                    ),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this rule last matched a request.",
                        null=True,
                        verbose_name="last hit at",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("auto", "Auto"),
                            ("signal", "Signal"),
                            ("import", "Import"),
                        ],
                        default="admin",
                        help_text="How this rule was created.",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Leave blank for single-tenant use.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this redirect rule.",
                        verbose_name="notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "redirect rule",
                "verbose_name_plural": "redirect rules",
                "db_table": "icv_sitemaps_redirect_rule",
                "ordering": ["priority", "source_pattern"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active", "priority"],
                        name="icv_sm_rdr_tnt_actv_pri_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("match_type", "exact")),
                        fields=("source_pattern", "tenant_id"),
                        name="icv_sm_rdr_src_tnt_exact_uniq",
                    )
                ],
            },
        ),
    ]
