# Generated by Django 6.0.3 on 2026-03-23 13:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_search", "0003_searchqueryaggregate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "field",
                    models.CharField(help_text="Document field to evaluate.", max_length=200),
                ),
                (
                    "field_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Value to compare against. Ignored for 'exists' operator.",
                        max_length=500,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("neq", "Not equals"),
                            ("gt", "Greater than"),
                            ("gte", "Greater than or equal"),
                            ("lt", "Less than"),
                            ("lte", "Less than or equal"),
                            ("contains", "Contains"),
                            ("exists", "Field exists"),
                        ],
                        default="eq",
                        help_text="Comparison operator.",
                        max_length=20,
                    ),
                ),
                (
                    "boost_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        help_text="Multiplicative weight. Values > 1 promote, values between 0 and 1 demote. Applied to the document's ranking score.",
                        max_digits=6,
                    ),
                ),
            ],
            options={
                "verbose_name": "boost rule",
                "verbose_name_plural": "boost rules",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QueryRedirect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(help_text="URL to redirect the user to.", max_length=2000),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("url", "External URL"),
                            ("category", "Category page"),
                            ("product", "Product page"),
                            ("page", "CMS page"),
                        ],
                        default="url",
                        help_text="Type of destination for analytics tracking.",
                        max_length=20,
                    ),
                ),
                (
                    "preserve_query",
                    models.BooleanField(
                        default=False,
                        help_text="Append the original query as a ?q= parameter to the destination URL.",
                    ),
                ),
                (
                    "http_status",
                    models.IntegerField(
                        choices=[(301, "301 Permanent"), (302, "302 Temporary")],
                        default=302,
                        help_text="HTTP status code for the redirect response.",
                    ),
                ),
            ],
            options={
                "verbose_name": "query redirect",
                "verbose_name_plural": "query redirects",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QueryRewrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "rewritten_query",
                    models.CharField(
                        help_text="The query string to use instead of the original.",
                        max_length=500,
                    ),
                ),
                (
                    "apply_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional filters to inject into the search request.",
                    ),
                ),
                (
                    "apply_sort",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sort order to inject into the search request.",
                    ),
                ),
                (
                    "merge_filters",
                    models.BooleanField(
                        default=True,
                        help_text="Merge injected filters with existing filters. When False, replaces them.",
                    ),
                ),
            ],
            options={
                "verbose_name": "query rewrite",
                "verbose_name_plural": "query rewrites",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Banner headline.", max_length=200),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Banner body content (supports HTML).",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional banner image URL.",
                        max_length=2000,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional click-through URL.",
                        max_length=2000,
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Call-to-action text for the link.",
                        max_length=200,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "Top of results"),
                            ("inline", "Inline within results"),
                            ("bottom", "Bottom of results"),
                            ("sidebar", "Sidebar"),
                        ],
                        default="top",
                        help_text="Where to display the banner relative to results.",
                        max_length=20,
                    ),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("informational", "Informational"),
                            ("promotional", "Promotional"),
                            ("warning", "Warning"),
                        ],
                        default="informational",
                        help_text="Semantic type of the banner for styling.",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata for custom rendering logic.",
                    ),
                ),
            ],
            options={
                "verbose_name": "search banner",
                "verbose_name_plural": "search banners",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(help_text="ID of the document to pin.", max_length=255),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Zero-based position in results. Use -1 to bury (push to end).",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label for the pin (e.g. 'sponsored', 'editorial pick').",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "search pin",
                "verbose_name_plural": "search pins",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZeroResultFallback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "fallback_type",
                    models.CharField(
                        choices=[
                            ("redirect", "Redirect to URL"),
                            ("alternative_query", "Run alternative query"),
                            ("curated_results", "Show curated document IDs"),
                            ("popular_in_category", "Show popular items in category"),
                        ],
                        help_text="Strategy to use when the original query returns zero results.",
                        max_length=30,
                    ),
                ),
                (
                    "fallback_value",
                    models.CharField(
                        help_text="Meaning depends on fallback_type: URL for redirect, query string for alternative_query, comma-separated IDs for curated_results, category identifier for popular_in_category.",
                        max_length=2000,
                    ),
                ),
                (
                    "fallback_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional filters applied when executing the fallback search.",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of fallback attempts before giving up.",
                    ),
                ),
            ],
            options={
                "verbose_name": "zero-result fallback",
                "verbose_name_plural": "zero-result fallbacks",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.RenameIndex(
            model_name="searchquerylog",
            new_name="icv_search__index_n_08e7ef_idx",
            old_name="icv_search__index_n_zero_idx",
        ),
        migrations.RenameIndex(
            model_name="searchquerylog",
            new_name="icv_search__index_n_09bc9e_idx",
            old_name="icv_search__index_n_tenant_idx",
        ),
        migrations.AddConstraint(
            model_name="searchpin",
            constraint=models.UniqueConstraint(
                fields=("index_name", "tenant_id", "query_pattern", "document_id"),
                name="icv_search_pin_unique",
            ),
        ),
    ]
